# Generated by Django 3.2.8 on 2021-12-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorReport',
            fields=[
                ('supervisor_report_id', models.IntegerField(blank=True, default=0, primary_key=True, serialize=False)),
                ('supervisor_id', models.IntegerField(blank=True, default=0)),
                ('total_calls_for_service', models.IntegerField(blank=True, default=0)),
                ('total_case_numbers_pulled', models.IntegerField(blank=True, default=0)),
                ('total_case_numbers_completed', models.IntegerField(blank=True, default=0)),
                ('total_reports', models.IntegerField(blank=True, default=0)),
                ('total_supplements', models.IntegerField(blank=True, default=0)),
                ('total_vehicles_assigned', models.IntegerField(blank=True, default=0)),
                ('total_miles_driven', models.IntegerField(blank=True, default=0)),
                ('officers_on_road', models.IntegerField(blank=True, default=0)),
                ('officers_on_desk', models.IntegerField(blank=True, default=0)),
                ('officers_on_jail_duty', models.IntegerField(blank=True, default=0)),
                ('officers_on_light_duty', models.IntegerField(blank=True, default=0)),
                ('officers_out_sick', models.IntegerField(blank=True, default=0)),
                ('officers_in_training', models.IntegerField(blank=True, default=0)),
                ('officers_on_vacation', models.IntegerField(blank=True, default=0)),
                ('officers_assigned_elswhere', models.IntegerField(blank=True, default=0)),
                ('total_citations_issued', models.IntegerField(blank=True, default=0)),
                ('total_warnings_issued', models.IntegerField(blank=True, default=0)),
                ('total_citizen_contacts', models.IntegerField(blank=True, default=0)),
                ('total_traffic_stops', models.IntegerField(blank=True, default=0)),
                ('total_arrest_made', models.IntegerField(blank=True, default=0)),
                ('total_juvenile_contacts', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
